// grid dummy data
var dummyData = {
	

	//"Cabbages":"<li class=\"product\"><div class=\"foodicon foodicon--lettuce\"></div></li><li class=\"product\"><div class=\"foodicon foodicon--lettuce\"></div></li><li class=\"product\"><div class=\"foodicon foodicon--lettuce\"></div></li><li class=\"product\"><div class=\"foodicon foodicon--lettuce\"></div></li><li class=\"product\"><div class=\"foodicon foodicon--lettuce\"></div></li><li class=\"product\"><div class=\"foodicon foodicon--lettuce\"></div></li><li class=\"product\"><div class=\"foodicon foodicon--lettuce\"></div></li><li class=\"product\"><div class=\"foodicon foodicon--lettuce\"></div></li><li class=\"product\"><div class=\"foodicon foodicon--lettuce\"></div></li><li class=\"product\"><div class=\"foodicon foodicon--lettuce\"></div></li><li class=\"product\"><div class=\"foodicon foodicon--lettuce\"></div></li><li class=\"product\"><div class=\"foodicon foodicon--lettuce\"></div></li><li class=\"product\"><div class=\"foodicon foodicon--lettuce\"></div></li><li class=\"product\"><div class=\"foodicon foodicon--lettuce\"></div></li><li class=\"product\"><div class=\"foodicon foodicon--lettuce\"></div></li><li class=\"product\"><div class=\"foodicon foodicon--lettuce\"></div></li><li class=\"product\"><div class=\"foodicon foodicon--lettuce\"></div></li><li class=\"product\"><div class=\"foodicon foodicon--lettuce\"></div></li><li class=\"product\"><div class=\"foodicon foodicon--lettuce\"></div></li><li class=\"product\"><div class=\"foodicon foodicon--lettuce\"></div></li><li class=\"product\"><div class=\"foodicon foodicon--lettuce\"></div></li><li class=\"product\"><div class=\"foodicon foodicon--lettuce\"></div></li><li class=\"product\"><div class=\"foodicon foodicon--lettuce\"></div></li><li class=\"product\"><div class=\"foodicon foodicon--lettuce\"></div></li>",

	//Introducao
	"Introdução":"<li class=\"product\"><div class=\"foodicon foodicon--desafios_iot\"><h1>Introdução</h1><h2>Desafios da IoT</h2>Muito tem-se discutido sobre IoT (ou <i>Internet of Things</i>). O \"futuro da Internet\", como tem sido chamado por muitos, almeja conectar objetos à Internet possibilitando a comunicação dos mesmos. Um objetivo simples, mas que se mostra extremamente ambicioso.<br/><br/>Podemos facilmente ser levados ao estado de êxtase ao ouvirmos as inúmeras aplicações da IoT, mas somos arrancados do mesmo ao compreender suas dificuldades de implementação. Estas, que aqui serão apresentadas, devem ser precedidas pelo que tomamos como o conceito de IoT e WSN.<br/><br/>Internet of Things ou \"Internet das Coisas\" refere-se a uma rede mundial (a exemplo da WWW- World Wide Web) de objetos interconectados com endereçamento único, baseado em protocolos padrão de comunicação.<br/><br/>Já o conceito de <i>Wireless Sensor Networks</i> ou \"Rede de sensores sem fio\" representa um grupo de sensores espaçados geograficamente que tem como finalidade monitorar elementos tais como temperatura e pressão, por exemplo.<br/><br/>Agora estamos prontos para entender os maiores obstáculos do desenvolvimento da IoT. O primeiro desafio é a conectividade. Em uma rede de altíssima densidade, tal como é, podemos ter diversos produtos de diversos fabricantes que desejam se comunicar: é necessário garantir que dados em formatos diversos possam ser interpretados.<br/><br/>O segundo desafio refere-se ao uso eficiente de energia, isso porque a maioria dos dispositivos WSN são ligados à bateria. Como o custo desses dispositivos é baixo, a troca da bateria é mais custosa do que repor o dispositivo por inteiro, o que torna seu tempo de vida limitado. Dessa forma, evidencia-se a necessidade de reduzir o consumo de energia sempre que possível.[1]<br/><br/>Um outro desafio de suma importância para a IoT é a segurança de dados. É preciso que uma informação seja transmitida e recebida de maneira íntegra em uma rede de altíssima densidade, tornando-se imprenscindível o uso de mecanismos de segurança.[1]<br/><br/>Na tentativa de diminuir esses problemas envolvidos em IoT, a empresa Semtech desenvolveu a tecnologia <i>Long Range</i> (LoRa), que é uma técnica de modulação <i>Spread Spectrum</i> derivada da tecnologia <i>Chirp Spread Spectrum</i>. Com LoRa, é possível ter uma rede sem fio de longo alcance e com consumo de energia reduzido. Nos próximos tópicos serão discutidos a topologia da rede, sua modulação e técnicas para reduzir o gasto de energia.<br/></div></li>",
	
	//Arquitetura
	"Topologia":"<li class=\"product\"><div class=\"foodicon foodicon--topologia\"><h1>Topologia</h1>A topologia de uma rede LoRa é composta pelos meios físico e digital e é organizada em camadas. Em seu mais baixo nível, há os sistemas-finais, todos podendo apresentar especificações diferentes quanto a sua bateria e a sua vazão para transmissão de dados. Esses dispositivos, por meio do protocolo <i>Long Range Wide Area Network</i> (LoRaWAN protocol), transmitem para e recebem dados de um <i>gateway</i>, conectados a um salto de distância (topologia do tipo <i>Star-of-Stars</i>. Os <i>gateways</i> funcionam como uma ponte de dados entre os dispositivos finais e a rede internet. Eles, por meio do protocolo de internet, transmitem para e recebem pacotes de um servidor.<div class=\"imageCaption\"><img src=\"img/topologia.png\" class=\"imagePadding\">Topologia da rede LoRa[1].</div></div></li>",
	

	"Módulos Gateway":"<li class=\"product\"><div class=\"foodicon foodicon--modulos_gateway\"> COMPLETAR </div></li>",
	

	"Protocolo LoRaWAN":"<li class=\"product\"><div class=\"foodicon foodicon--lorawan\"><h1>Protocolo LoRaWAN</h1>LoRaWAN (<i>Long Range Network Protocol</i>) é um protocolo do tipo <i>Low Power Wider Area Networking</i> (LPWAN) relativamente novo, que abrange dispositivos de comunicação bidirecional alimentados por bateria [1], e já se tornou o foco de inúmeros centros de pesquisa ao redor do mundo. A especificação LoRaWAN garante a perfeita interoperalidade entre os objetos de IoT, sem requerer implementações locais mais complexas [3].<br/><br/>O Protocolo LoRaWAN é responsável pelos níveis mais baixos da topologia da rede LoRa. Ele oferece segurança, ajuste de consumo de dados e adaptação à variados dispositivos finais e faz o transporte de dados entre <i>Gateways</i> e Dispositivos Finais. Um pacote do protocolo LoRaWAN, seja de <i>Uplink</i> ou de <i>Downlink</i> carregam um <i>payload</i> da camada física (PHY), começando com um cabeçalho MAC (MHDR), seguido de um <i>payload</i> MAC (MACPayload) e termina com um código que avalia a integridade da mensagem, <i>message integrity code</i> (MIC) [5].<div class=\"imageCaption\"><img = src=\"img/pacoteLorawan.png\" class=\"imagePadding\">Estruturação de um pacote LoRaWAN [5].</div><br/><div class=\"imageCaption\"><img = src=\"img/loraMessageTypes.png\" class=\"imagePadding\">Tipos de Mensagens do protocolo LoRaWAN [5].</div><br/>As vantagens da tecnologia LoRaWAN incluem o uso de uma faixa de frequência não-licensiada (ISM), a fácil adaptação desse protocolo para um problema específico, a segurança dessa rede graças aos algorítimos de criptografia que ela utiliza e a comunicação bidirecional que ela promove.</div></li>",
	
	//Dispositivos Finais

	"Dispositivos Finais":"<li class=\"product\"><div class=\"foodicon foodicon--lorawan\"><h1>Dispositivos Finais</h1>A rede LoRa, tecnologia derivada dos obstáculos de IoT, comporta dispositivos finais de diversas especificações técnicas. Em primeiro lugar, como um dos objetivos de IoT é acumular a maior quantidade de dados possíveis sobre diversas situações e aparelhos, entende-se que os dispositivos-finais que a rede LoRa tem o dever de atingir são sensores. Sensores esses que, em sua maioria, tem sua fonte de potência advinda de baterias e, portanto, há uma necessidade constante de reduzir seu custo de energia [1]. Para lidar com isso, foram criadas três classificações diferentes para os dispositivos finais, levando em conta o fator consumo de energia, assim como, integralmente com o protocolo LoRaWAN, foi desenvolvida a tecnologia <i>Adaptive Data Rate</i> (ADR).</div></li>",

	"Classes de Dispositivos":"<li class=\"product\"><div class=\"foodicon foodicon--adr\"><h1>Classes de Dispositivos</h1>A tecnologia LoRa possui vários tipos de \"dispositivos finais\". Dependendo das especificações de cada um e do mecanismo de comunicação implementado, podemos ter três classificações diferentes. São elas:<h2>Classe A</h2>Dispositivos dessa classe possuem recursos de comunicação bidirecional. O intervalo de tempo durante a transmissão é seguido por outros dois intervalos curtos, durante os quais o dispositivo pode receber outras informações. Nessa categoria, só se pode receber dados do servidor depois que as informações já foram enviadas, o que garante a maior eficiência energética dentre as três classes de LoRa[1]. Essa classe é recomendada para dispositivos de bateria reduzia pois garante um consumo reduzido de energia. Quando uma mensagem é enviada pelo dispositivo final por meio do uplink, duas janelas, RX1 e RX2, são abertas para o recebimento de transmissões do servidor. Assim que abertas as janelas, incia-se um timer para cada, sendo timer para a janela RX1 < timer para a janela RX2. No caso de o timer da janela RX1 acabar antes de um ACK do servidor ser recebido, a janela é fechada, fazendo com que a espera do ACK agora seja responsabilidade de RX2. Se nada for recebido quando o timer de RX2 chegar a zero, o dispositivo final reenvia a mensagem inicial, entendendo que pode ter ocorrido uma falha de conexão [4].<br/><div class=\"imageCaption\"><img src=\"img/classA.png\" alt=\"Janelas de recebimento de ACK do serivdor\" class=\"imagePadding\">Procedimento da troca de mensagens para dispositivos classe A [4].</div><br/><br/><h2>Classe B</h2>Dispositivos com essa classificação possuem, além das especificações da Classe A, um intervalo de tempo adicional que permite o recebimento de dados durante a comunicação. Além disso, eles podem fazer uso de uma série de 'slots' de recepção, que por sua vez são ativados por um tipo de mensagem 'Beacon'[1].<h2>Classe C</h2>A principal diferença entre os dispositivos desse tipo e os da Classe B é que podem existir mais de um intervalos de tempo, o que permite o recebimento de uma quantidade ilimitada de informações. A única circunstância em que essa característica não se aplica é quando o próprio dispositivo da Classe C é quem está enviando a informação[1].<br/><br/> Vale ressaltar que, dentro das especificações da LoRa Padrão, cada módulo deve obrigatoriamente implementar o mecanismo de comunicação da Classe A. As especificações das demais classes são opicionais.</div></li>",

	"Adaptive Data Rate (ADR)":"<li class=\"product\"><div class=\"foodicon foodicon--adr\"><h1>Adaptive Data Rate (ADR)</h1>A tecnologia ADR é parte das especificações do protocolo LoRaWAN [9]. Seu objetivo principal é ajustar as variáveis <i>Spreading Factor</i> (SF) e <i>Transmission Power</i> (TP) para equilibrar o consumo e a eficiência dos dispositivos finais, assim como controlar o uso dos canais de rádio.<br/><br/>Se um dispositivo final detecta que não está recebendo informações depois de uma série de transmissões <i>uplink</i>, ele entende que houve falha na conexão e resolve o problema aumentando o valor de seu <i>Transmission Power</i> para o máximo e, em seguida, caso ainda não haja resposta, aumenta seu <i>Spreading Factor</i> até o máximo, da mesma forma[9]. Essas mudanças permitem que o laço que conecta o dispositivo final tenha mais chance de ser refeito.<br/><br/>Um dispositivo final pode pedir à rede para monitorar a qualidade do <i>uplink</i> de recepções de um passado recente. Se as configurações para o <i>Spreading Factor</i> e para o <i>Transmission Power</i> forem muito maiores das utilizadas nas últimas <i>N</i> transmissões, a rede decide reduzir essas variáveis, de forma a reduzir o consumo de energia[9].</div></li>",

	//Modulação LoRa
	"Chirp Spread Spectrum":"<li class=\"product\"><div class=\"foodicon foodicon--chirp_spread_spectrum\"><h1>Chirp Spread Spectrum</h1>A modulação de sinais na arquitetura LoRa é feita através do Chirp Spread Spectrum.  Um pulso chirp é um sinal cuja frequência varia monotonamente. Se aumentamos a frquência temos um \"Up-chirp\" e se ela decresce temos um \"Down-Chirp\". A justificativa para o uso deste tipo de modulação está nos diversos benefícios que o mesmo proporciona, vantagens que sem as quais a arquitetura LoRa seria incapaz de operar. Ou seja, as ditas vantagens são, para LoRa,  uma questão de necessidade.<br/><br/>Primeiro temos que entender que WSN podem trabalhar com dados sensíveis e precisamos garantir a integridade física dos mesmos da emissão a recepção. É necessário que qualquer sinal emitido seja robusto, ou seja, que não propague ruídos, apresente resistência a diferentes meios e não sofra interferência na sua faixa de frequência (por conta dos inúmeros dispositivos que podem operar de maneira semelhante).<br/><br/>Outra necessidade da arquitetura se trata do consumo de energia que precisa ser extremamente baixo. Bem como o alcance de um sinal emitido seja suficientemente grande para honrar com o nome da arquitetura. Será que o CSS dá conta disso?<br/><br/>COMPLETAR </div></li>",


	//Conclusões
	"Conclusões":"<li class=\"product\"><div class=\"foodicon foodicon--chirp_spread_spectrum\">COMPLETAR</div></li>",
	
	//Bibliografia
	"Bibliografia":"<li class=\"product\"><div class=\"foodicon foodicon--chirp_spread_spectrum\"><h1>Bibliografia</h1>[1] Lavric, A., \& Popa, V. (2017). Internet of Things and LoRa™ Low-Power Wide-Area Networks: A survey. 2017 International Symposium on Signals, Circuits and Systems (ISSCS).<br/><br/>[2] Sinha, R. S., Wei, Y., \& Hwang, S.-H. (2017). A survey on LPWA technology: LoRa and NB-IoT. ICT Express, 3(1), 14–21.<br/><br/>[3] Semtech Company https://www.semtech.com/lora última data de acesso: 08/05/2019<br/><br/>[4] Chékra El Fehri, Mohamed Kassab, Slim Abdellatif, Pascal Berthou, Abdelfettah Belghith (2018). LoRa technology MAC layer operations and Research issues. The Fourth International Workshop on Recent Advances on Internet of Things (RAMCOM 2018).<br/><br/>[5] LoRa Alliance, A technical overview of LoRa and  LoRaWAN,https://www.lora-alliance.org/what-is-lora (2015).<br/><br/>[6] Oratile Khutsoane, Bassey Isong, Adnan M. Abu-Mahfouz. (2017). IoT Devices and Applications based on LoRa/LoRaWAN.<br/><br/>[7] Jansen C. Liando, Amalinda Gamage, Agustinus W. Tengourtius, Mo Li. (2018). Known and Unknown Facts of LoRa: Experiences from a Large Scale Measurement Study. ACM Trans. Sensor Netw. 0, 0, Article 19<br/><br/>[8] Gianni Pasolini, Chiara Buratti, Luca Feltrin 1, Flavio Zabini, Cristina De Castro 2, Roberto Verdone, Oreste Andrisano. (2018). Smart City Pilot Projects Using LoRa and IEEE802.15.4 Technologies<br/><br/>[9] Li, S. Raza, U. Khan, A. (2014) How Agile is the Adaptive Data Rate Mechanism of LoRaWAN? Telecommunications Research Laboratory, Bristol, UK. University of Bristol, Bristol, UK<br/></div></li>"

}
